force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Contact_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Contact_Preferences__c</fullName>
    <label>Contact Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Needs_Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Needs_Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Follow Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Email__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Email__c</fullName>
    <label>Receiver Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_First_Name__c</fullName>
    <label>Receiver First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Last_Name__c</fullName>
    <label>Receiver Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Phone_Number__c</fullName>
    <label>Receiver Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <label>Referral ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Sender_Username__c.field-meta.xml
<CustomField>
    <fullName>Sender_Username__c</fullName>
    <label>Sender Username</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>couldnt_get_help</fullName>
                <label>couldn’t get help</label>
            </value>
            <value>
                <fullName>got_help</fullName>
                <label>got help</label>
            </value>
            <value>
                <fullName>needs_action</fullName>
                <label>needs action</label>
            </value>
            <value>
                <fullName>no_longer_interested</fullName>
                <label>no longer interested</label>
            </value>
            <value>
                <fullName>not yet helped</fullName>
            </value>
            <value>
                <fullName>referred elsewhere</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
            <value>
                <fullName>couldn’t contact</fullName>
            </value>
            <value>
                <fullName>not eligible</fullName>
            </value>
            <value>
                <fullName>eligible</fullName>
            </value>
            <value>
                <fullName>no capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/auntBerthaCBO.cls
public with sharing class auntBerthaCBO
{
    public auntBerthaCBO() {

    }

    @AuraEnabled
    public static List<Referral__c> getAllReferrals(){
        List<Referral__c> lR = [SELECT Id, Referral_ID__c, Program__c, Status__c, Name, Needs_Follow_Up__c FROM Referral__c];
        return lR;
    }

    @AuraEnabled
    public static Referral__c getSingleReferral(Id rId) {
 
        System.debug('from main record: rId [' + rId + ']');

        return [
            SELECT Id, Referral_ID__c, Program__c, Name, Sender_Username__c, Receiver_First_Name__c, Receiver_Last_Name__c, Receiver_Email__c,
            		Receiver_Phone_Number__c, Status__c, Comment__c, Contact_Preferences__c, Needs_Follow_Up__c
            FROM Referral__c where Id = :rId
        ];
    }

    @AuraEnabled
    public static string sendStatusToEndpoint(String referralId, String newStatus){
        System.debug('in sendStatusToEndpoint');

        System.debug('referralId [' + referralId + '] status [' + newStatus + ']');
         
        /*try {

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }*/

        return 'success';
    }

}