force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Program_ID__c</fullName>
    <externalId>true</externalId>
    <label>Program ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Email__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Email__c</fullName>
    <label>Receiver Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_First_Name__c</fullName>
    <label>Receiver First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Last_Name__c</fullName>
    <label>Receiver Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Receiver_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Phone_Number__c</fullName>
    <label>Receiver Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Sender_Username__c.field-meta.xml
<CustomField>
    <fullName>Sender_Username__c</fullName>
    <label>Sender Username</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>couldnt_get_help</fullName>
                <label>couldn’t get help</label>
            </value>
            <value>
                <fullName>got_help</fullName>
                <label>got help</label>
            </value>
            <value>
                <fullName>needs_action</fullName>
                <label>needs action</label>
            </value>
            <value>
                <fullName>no_longer_interested</fullName>
                <label>no longer interested</label>
            </value>
            <value>
                <fullName>not yet helped</fullName>
            </value>
            <value>
                <fullName>referred elsewhere</fullName>
            </value>
            <value>
                <fullName>unknown</fullName>
            </value>
            <value>
                <fullName>couldn’t contact</fullName>
            </value>
            <value>
                <fullName>not eligible</fullName>
            </value>
            <value>
                <fullName>eligible</fullName>
            </value>
            <value>
                <fullName>no capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferralController.cls
public class ReferralController
{
    @AuraEnabled(cacheable=true)
    public static List<Referral__c> findReferrals(String searchKey) {
        String key = '%' + searchKey + '%';
        return [
            SELECT Id, Program_Id__c, Sender_Username__c
            FROM Referral__c
            WHERE Program_Id__c LIKE :key AND Sender_Username__c != NULL
            WITH SECURITY_ENFORCED
            LIMIT 10
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Referral__c getSingleReferral() {
        return [
            SELECT Id, Program_Id__c, Sender_Username__c, Receiver_First_Name__c, Receiver_Last_Name__c, Receiver_Email__c,
            		Receiver_Phone_Number__c, Status__c
            FROM Referral__c
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }

}